config/routes.rb
Rails.application.routes.draw do
  	get 'sites/edit'
  	get 'sites/update'
	get 'pages/index'
	get 'pages/new'
	get 'pages/show'
	get 'pages/edit'
	get 'password_resets/new'
	get 'password_resets/edit'


	#Root
	root 'routes#root'


	#Users
	resources :users, except: [:new, :show ]
	get '/signup', to: "users#new"


	#Sessions
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout', to: "sessions#destroy"

	
	#Activations
	resources :account_activations, only: [:edit]

	
	#Resets
	resources :password_resets, only: [:new, :create, :edit, :update]

	
	#Pages
	resources :pages, only: [:index, :show, :edit] do
		member do
			delete :delete_image_attachment
		end
	end
	
	patch '/pages/:id/increment', to: "pages#increment", as: 'increment_pages'
	patch '/pages/:id/decrement', to: "pages#decrement", as: 'decrement_pages'

	resources :tmp_groups, controller: :pages, type: "TmpGroup", except: [:index, :show, :edit]
	resources :tmp_articles, controller: :pages, type: "TmpArticle", except: [:index, :show, :edit]
	resources :tmp_galleries, controller: :pages, type: "TmpGallery", except: [:index, :show, :edit]
	resources :tmp_cards, controller: :pages, type: "TmpCard", except: [:index, :show, :edit]
	resources :tmp_splashes, controller: :pages, type: "TmpSplash", except: [:index, :show, :edit]
	resources :tmp_links, controller: :pages, type: "TmpLink", except: [:index, :show, :edit]

	#Site
	get '/options', to: "sites#edit"
	patch '/options', to: "sites#update"
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save :downcase_email
	before_create :create_activation_digest

	validates   :name, 
					presence: true,
					length: { maximum: 50 }
	validates	:email,
					presence: true,
					length: { maximum: 200 },
					format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i },
					uniqueness: { case_sensitive: false }
	validates	:password,
					presence: true,
					length: { minimum: 6 },
					allow_nil: true

	has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
													  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# returns a random token
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Forgets a user.
	def forget
		update_attribute(:remember_digest, nil)
	end
	
	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	# Activates an account.
	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end
	
	# Sends activation email.
	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	# Sets the password reset attributes
	def create_reset_digest
		self.reset_token = User.new_token
		update_attribute(:reset_digest, User.digest(reset_token))
		update_attribute(:reset_sent_at, Time.zone.now)
	end

	# Sends the reset email
	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	# Checks if reset token has expired
	def password_reset_expired?
		reset_sent_at < 2.hours.ago
	end
	
	private

		# Creates and assigns the activation token and digest.
		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end

		# Converts an email address to all lowercase
		def downcase_email
			self.email.downcase!
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:edit, :update]
	before_action :correct_user, only: [:edit, :update]
  
	def index
		@users = User.order(admin: :desc, name: :asc).paginate(page: params[:page])
	end

	def new
		@user = User.new
	end

	def create
	@user = User.new(user_params)

		if @user.save
			@user.send_activation_email
			flash[:success] = "Successfully Sent Activation Email to #{@user.email}"
			redirect_to root_url
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		if !logged_in?
			flash[:warning] = "You Must Log In"
			redirect_to login_path
		elsif user_admin?
			#does nothing but exit the if-tree and continue
		elsif @user != current_user
			flash[:warning] = "Please Log In as that User to View Their Profile."
			redirect_to root_url
		elsif !@user.activated
			flash[:warning] = "User Not Activated. Please Activate Via Email First."
			redirect_to root_url
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			flash[:success] = "Updated #{@user.name}!"
			redirect_to(root_url)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])

		@user.destroy
		redirect_to users_path
	end

	private 
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end

		#before filters

		#confirms a logged-in user
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = "Please Log In"
				redirect_to login_url
			end
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_url) unless current_user?(@user) || user_admin?
		end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="col-sm-4 col-sm-offset-4 col-xs-12">
    <%= form_for @user do |f| %>
        
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label "Name"%>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label "Email Address" %>
            <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label "Password" %>
            <%= f.password_field :password, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label "Confirm Password" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <hr>
        <%= f.submit yield(:button_text), class: "btn btn-block btn-primary" %>

        <% if !logged_in? %>
            <p>Already a User? <%= link_to "Log In", login_path%></p>
        <% end %>

    <% end %>
</div>

app/views/users/_user.html.erb
<tr>
    <td class="text-center"><%= user.name %></td>
    <td class="text-center"><%= user.email %></td>
    <td class="text-center">
        <%= check_box_tag("Admin", user.admin, user.admin, :disabled => true) %>
    </td>
    <td class="text-center"><%= user.created_at %></td>
    <td class="text-center"><%= user.updated_at %></td>
    <td class="text-center"><%= link_to "View", user, class: "btn btn-block btn-xs btn-primary" %></td>
    <td class="text-center"><%= link_to "Edit", edit_user_path(user.id), class: "btn btn-block btn-xs btn-warning" %></td>
    <td class="text-center"><%= link_to "Delete", user, method: :delete, class: "btn btn-block btn-xs btn-danger", data: { confirm: "Are you sure you want to delete #{user.name}?\n\nTHIS CANNOT BE UNDONE!" } %></td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:button_text, 'Save Changes') %>

<div class="page-header">
    <h1>Update <%= @user.name %></h1>
    <% if user_admin? %>
        <%= link_to "<< All Users", users_path, class: "btn btn-default" %>
    <% end %>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<div class="page-header">
    <h1>All Users</h1>
</div>
<div class="col-md-12">
    <%= will_paginate @users %>
    <table class="table table-condensed table-bordered table-striped">
        <tr>
            <th class="text-center">User Name</th>
            <th class="text-center">Email</th>
            <th class="text-center">Admin</th>
            <th class="text-center">Date Created</th>
            <th class="text-center">Date Edited</th>
            <th class="text-center">View User</th>
            <th class="text-center">Edit User</th>
            <th class="text-center">Delete User</th>
        </tr>
    <%= render @users %>
    </table>
    <%= will_paginate @users %>
</div>
<hr>
<%= link_to "New User", signup_path, class: "btn btn-primary" %>

app/views/users/new.html.erb
<% provide(:title, 'New User') %>
<% provide(:button_text, 'Create Account') %>

<div class="page-header col-sm-4 col-sm-offset-4 col-xs-12">
    <%= user_admin? ? tag.h1("Add User") : tag.h1("Sign Up!") %>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="secondary-background col-sm-3 col-xs-12">
    <h2>
        <%= @user.name %>
        <% if @user.admin %>
            <small><small>(Admin)</small></small>
        <% end %>
    </h2>
    <h4><%= @user.email %></h4>
    
    <%= link_to "Edit User", edit_user_path(params[:id]), class: "btn btn-block btn-primary" %>
    <hr>
</div>
<div class="col-md-9 col-xs-12">
    <h4>User Content Will Go here Eventually</h4>
</div>