config/routes.rb
Rails.application.routes.draw do
  	get 'sites/edit'
  	get 'sites/update'
	get 'pages/index'
	get 'pages/new'
	get 'pages/show'
	get 'pages/edit'
	get 'password_resets/new'
	get 'password_resets/edit'


	#Root
	root 'routes#root'


	#Users
	resources :users, except: [:new, :show ]
	get '/signup', to: "users#new"


	#Sessions
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout', to: "sessions#destroy"

	
	#Activations
	resources :account_activations, only: [:edit]

	
	#Resets
	resources :password_resets, only: [:new, :create, :edit, :update]

	
	#Pages
	resources :pages, only: [:index, :show, :edit] do
		member do
			delete :delete_image_attachment
		end
	end
	
	patch '/pages/:id/increment', to: "pages#increment", as: 'increment_pages'
	patch '/pages/:id/decrement', to: "pages#decrement", as: 'decrement_pages'

	resources :tmp_groups, controller: :pages, type: "TmpGroup", except: [:index, :show, :edit]
	resources :tmp_articles, controller: :pages, type: "TmpArticle", except: [:index, :show, :edit]
	resources :tmp_galleries, controller: :pages, type: "TmpGallery", except: [:index, :show, :edit]
	resources :tmp_cards, controller: :pages, type: "TmpCard", except: [:index, :show, :edit]
	resources :tmp_splashes, controller: :pages, type: "TmpSplash", except: [:index, :show, :edit]
	resources :tmp_links, controller: :pages, type: "TmpLink", except: [:index, :show, :edit]

	#Site
	get '/options', to: "sites#edit"
	patch '/options', to: "sites#update"
end

app/models/tmp_gallery.rb
class TmpGallery < Template
    has_many_attached :images

end

app/views/tmp_galleries/_form.html.erb
<% # NEW Gallery Page %>

<div class="col-sm-8 col-sm-offset-2 col-xs-12">
    <%= form_for(item) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.submit yield(:button_text), class: "btn btn-block btn-primary" %>
        
        <%= render partial: '/pages/basic', locals: { f: f, item: item } %>

        <% image_count = item.images.count%>
        <% if image_count > 0%>
            <%= render partial: '/tmp_galleries/table', locals: { item: item } %>
        <% end %>

        <h3 class="section-heading">Add Image(s)</h3>
        <div class="form-group">
            <%= f.label :images %>
            <%= f.file_field :images, multiple: true, direct_upload: true, class: "form-control" %>
        </div>
        
        <%= f.submit yield(:button_text), class: "btn btn-block btn-primary" %>

    <% end %>
</div>

app/views/tmp_galleries/_new.html.erb
<% # NEW Gallery Page %>

<div class="col-md-8 col-md-offset-2 col-sm-12">
    <%= form_for(:tmp_gallery, url: site_item_tmp_galleries_path) do |f| %>
        
        <%= render 'shared/error_messages' %>

        <div class="form-group">
            <%= f.label "Name"%>
            <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label "Subtitle"%>
            <%= f.text_field :subtitle, class: "form-control" %>
        </div>
        <div class="form-group">
            <%= f.label "Description" %>
            <%= f.text_area :description, class: "form-control" %>
        </div>
        
        <hr/>
        <%= f.submit yield(:button_text), class: "btn btn-block btn-primary" %>

    <% end %>
</div>

app/views/tmp_galleries/_show.html.erb
<% # GALLERY TEMPLATE %>

<div>
    <div>
        <% item.images.each do |image| %>
            <div class="gallery-frame col-lg-3 col-md-4 col-sm-6 col-xs-12 filter hdpe">
                <%= link_to( image_tag(image, alt: image.filename, class: "gallery"), image, target: "_blank") %>
            </div>
        <% end %>
    </div>
</div>

app/views/tmp_galleries/_table.html.erb
<h3>Images</h3>
<table class="table table-condensed table-bordered table-striped">
    <tr>
        <th><strong>Thumbnail</strong></th>
        <th class="text-center"><strong>Delete</strong></th>
    </tr>
    <% item.images.each do |image| %>
        <tr>
            <td class="text-center"><%= link_to( image_tag(image, alt: image.filename, class: "table"), image, target: "_blank") %></td>
            <td><%= link_to "Delete", delete_image_attachment_page_path(image.signed_id, item.id), method: :delete, data: { confirm: 'Are you sure? THIS CANNOT BE UNDONE!' }, class: "btn btn-block btn-sml btn-danger" %></td>
        </tr>
    <% end %>
</table>
<hr>

app/views/tmp_galleries/_tmp_gallery.html.erb
<%= render partial: '/pages/item_index', locals: {item: tmp_gallery, type: tmp_gallery.type[3..-1] }%>