config/routes.rb
Rails.application.routes.draw do
  	get 'sites/edit'
  	get 'sites/update'
	get 'pages/index'
	get 'pages/new'
	get 'pages/show'
	get 'pages/edit'
	get 'password_resets/new'
	get 'password_resets/edit'


	#Root
	root 'routes#root'


	#Users
	resources :users, except: [:new, :show ]
	get '/signup', to: "users#new"


	#Sessions
	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout', to: "sessions#destroy"

	
	#Activations
	resources :account_activations, only: [:edit]

	
	#Resets
	resources :password_resets, only: [:new, :create, :edit, :update]

	
	#Pages
	resources :pages, only: [:index, :show, :edit] do
		member do
			delete :delete_image_attachment
		end
	end
	
	patch '/pages/:id/increment', to: "pages#increment", as: 'increment_pages'
	patch '/pages/:id/decrement', to: "pages#decrement", as: 'decrement_pages'

	resources :tmp_groups, controller: :pages, type: "TmpGroup", except: [:index, :show, :edit]
	resources :tmp_articles, controller: :pages, type: "TmpArticle", except: [:index, :show, :edit]
	resources :tmp_galleries, controller: :pages, type: "TmpGallery", except: [:index, :show, :edit]
	resources :tmp_cards, controller: :pages, type: "TmpCard", except: [:index, :show, :edit]
	resources :tmp_splashes, controller: :pages, type: "TmpSplash", except: [:index, :show, :edit]
	resources :tmp_links, controller: :pages, type: "TmpLink", except: [:index, :show, :edit]

	#Site
	get '/options', to: "sites#edit"
	patch '/options', to: "sites#update"
end

app/views/layouts/_footer.html.erb
<% site = Site.first %>
<%= raw("<footer class=\"text-center footer navbar-inverse\" style=\"background-color: #{site.navbar_color}\">") %>
    <p>Built and Maintained by Chuck Crouse | <%= link_to("chucksef.com", "https://www.chucksef.com", style: "color: #{site.primary_color}" ) %></p>
<%= raw("</footer>") %>

app/views/layouts/_header.html.erb
<% site = Site.first %>

<% # ALLOW JS TO SEE @SITE PROPERTIES %>
<%= content_tag(:div, id: "site-information", data: {primary_color: site.primary_color, secondary_color: site.navbar_color}) do %>
<% end %>

<%= raw("<header class=\"navbar navbar-fixed-top navbar-inverse container-fluid\" style=\"background-color: #{site.navbar_color}\">") %>
    <div class="header-logo">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <%= content_tag(:span,"", class: "icon-bar", style: "background-color: #{site.primary_color} !important") %>
        <%= content_tag(:span,"", class: "icon-bar", style: "background-color: #{site.primary_color} !important") %>
        <%= content_tag(:span,"", class: "icon-bar", style: "background-color: #{site.primary_color} !important") %>
        </button>
        <%=  %>
        <%= link_to inline_svg_tag("CC code.svg", class: "img-logo", style: "fill: #{site.primary_color}") +"#{site.name}", root_path, class: "navbar-brand", id: "logo", style: "color: #{site.primary_color}"%>
    </div>

    <% # SITE NAV SECTION OF NAVBAR %>
    <%= raw("<nav id=\"navbar\" class=\"navbar-collapse collapse\" style=\"border-color: #{site.primary_color}\">") %>
        <ul class="nav navbar-nav">
            <% Page.order(order: :asc).all.each do |item| %>
                <%= render partial: 'layouts/nav_item', locals: { item: item, color: site.primary_color, bg_color: site.navbar_color } %>
            <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            
            <% # ADMIN SECTION OF NAVBAR %>    
            <% if user_admin? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Admin 
                        <%= content_tag(:b, "", class:"caret", style: "color: #{site.primary_color}" ) %>
                    </a>
                    <%= raw("<ul class=\"dropdown-menu\" style=\"background-color: #{site.navbar_color}\">")%>
                        <li><%= link_to "Manage Pages", pages_path, style: "color: #{site.primary_color}" %>
                        <%= content_tag(:li, "", class: "divider") %>
                        <li><%= link_to "Users", users_path, style: "color: #{site.primary_color}" %></li>
                        <%= content_tag(:li, "", class: "divider") %>
                        <li><%= link_to "Site Options", options_path, style: "color: #{site.primary_color}" %>
                    </ul>
                </li>
            <% end %>

            <% # LOGIN SECTION OF NAVBAR%>
            <% if logged_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account 
                    <%= content_tag(:b, "", class:"caret", style: "color: #{site.primary_color}" ) %>
                    </a>
                    <%= raw("<ul class=\"dropdown-menu\" style=\"background-color: #{site.navbar_color}\">")%>
                        <li><%= link_to "Edit Account", edit_user_path(current_user), style: "color: #{site.primary_color}" %></li>
                        <%= content_tag(:li, "", class: "divider") %>
                        <li>
                            <%= link_to "Log out", logout_path, method: :delete, style: "color: #{site.primary_color}" %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li><%= link_to "Log-In", login_path %></li>
            <% end %>
        </ul>
    </nav>
<%= raw("</header>") %>

app/views/layouts/_nav_item.html.erb
<% if item.type == "TmpLink" && !item.tmp_group_id %>
    <%= content_tag(:li, link_to(item.name, item.description, :target => "_blank")) if item.visible && item.order != 1 %>
<% elsif item.type != "TmpGroup" && !item.tmp_group_id %>
    <%= content_tag(:li, link_to(item.name, page_path(item))) if item.visible && item.order != 1 %>
<% elsif item.tmp_group_id %>
    <%# THIS ELSIF IS NECESSARY TO CONTROL FOR EDGE CASES %>
<% elsif item.visible %>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{item.name} " %><%= content_tag(:b, "", class:"caret", style: "color: #{color}" ) %></a>
        <%= raw("<ul class=\"dropdown-menu\" style=\"background-color: #{bg_color}\">")%>
            <% item.pages.order(order: :asc).each do |sub| %>
                <%= content_tag(:li, link_to(sub.name, page_path(sub), style: "color: #{color}")) if sub.visible && sub.type != "TmpLink" %>
                <%= content_tag(:li, link_to(sub.name, sub.description, :target => "_blank", style: "color: #{color}")) if sub.visible && sub.type == "TmpLink" %>
            <% end %>
        </ul>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= get_page_title(yield(:title)) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,500&display=swap" rel="stylesheet">

	</head>

	<body class="<%= controller_name %> <%= action_name %>">
		<%= render 'layouts/header' %>
		<div class="container-fluid" id="page_container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, id: "flash", class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
		</div>
		
		<% debug(params) if Rails.env.development? %>
		<%= render 'layouts/footer' %>
	</body>
</html>